version: '3.8'

services:
  frontend:
    image: frontend
    container_name: front_container
    build:
      context: front
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - backend
    networks:
      - front-end
      - back-end

  backend:
    image: backend
    container_name: back_container
    build:
      context: back
    environment:
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - 8080:8080
    restart: always
    #depends_on:
      #- db
    networks:
      - back-end

networks:
  back-end:
  front-end: