version: '3'

services:
  front:
    image: frontend
    container_name: front
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - back
    networks:
      - front-end
      - back-end

  back:
    image: backend
    container_name: back
    build:
      context: .
      dockerfile: back/Dockerfile
    ports:
      - 8080:8080
    restart: always
    #depends_on:
      #- db
    networks:
      - back-end

networks:
  back-end:
  front-end: