version: '3.8'

services:
  frontend:
    image: frontend
    container_name: front_container
    build:
      context: front
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - backend
    # networks:
    #   - front-end

  backend:
    image: backend
    container_name: back_container
    build:
      context: back
    environment:
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
    network_mode: host
    # networks:
    #   - front-end
    #   - back-end

  db:
    image: mongodb/mongodb-community-server
    container_name: db_container
    ports:
      - 27017:27017
    restart: always
    # networks:
    #   - back-end
    #   - interface

  mongo-interface:
    image: mongo-express
    container_name: mongo_interface_container
    environment:
      - ME_CONFIG_MONGODB_SERVER=localhost
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - 8081:8081
    depends_on:
      - db
    network_mode: host
    # networks:
    #   - interface

# networks:
#   back-end:
#   front-end:
#   interface: