version: '3.8'

services:
  frontend:
    image: frontend
    container_name: front_container
    build:
      context: front
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    #environment:
      #- REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - 3000:80
    restart: always
    networks:
      - front-end



  db:
    image: mongodb/mongodb-community-server
    container_name: db_container
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=12345
    ports:
      - 27017:27017
    restart: always
    hostname: mongo
    networks:
      - back-end
      - interface

  mongo-interface:
    image: mongo-express
    container_name: mongo_interface_container
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://admin:12345@mongo:27017
    ports:
      - 8081:8081
    depends_on:
      - db
    networks:
      - interface
      
      
  redis:
    image: redis:6.2-alpine
    container_name: redis_container
    ports:
      - 6379:6379
    restart: always
    hostname: redis
    networks:
      - interface


networks:
  back-end:
  interface:
  front-end: